### ISSUE TITLE
default TMPDIR issue

### ISSUE THREAD

**Issue by fswarbrick** [zopencommunity/ctagsport#6]
It appears that if the TMPDIR environment variable is not set, ctags will default it to "/jenkins/PortBuild/tmp".  Example:
```$ bash -c "ctags -f - --sort=no --fields=n main.go"
ctags: cannot open temporary file: /jenkins/PortBuild/tmp/tags.BgfgxQ : EDC5129I No such file or directory.
```
This can be worked around by setting TMPDIR appropriately:
```
TMPDIR=/tmp bash -c "ctags -f - --sort=no --fields=n main.go"
```
Using current ctagsport version heads.v6.1.0.20240102_022406.

**Comment by HarithaIBM** [comment]
The issue is fixed as part of https://github.com/zopencommunity/ctagsport/pull/8
